# Continuous Random Variables
In the last chapter, we learned about discrete random variables, expectation and variance, and some common distributions. In this chapter we will explore similar concepts for random variables with continuous spaces. We also get to learn about one of the most special and wonderful distributions, which, for some reason has a very benign name - the normal distribution.

## Probability Density and the Continuous Random Variable
We'll start our discussion by highlighting the difficulty in describing probability for continuous random variables. Suppose we are trying to define a probability distribution for a continuous random variable that has some probability for each value in - $0 \leq X \leq 1$. That is, all the outcomes in the range from 0 to 1 (including 0 and 1) have $p(x) > 0$. Further suppose that we proceed as we would for a discrete random variable. That is, we take a probability mass of 1 and spread it around over the support of the values of $X$. 

Because of the properties of a pmf, we would need to make sure that for all the $n$ outcomes in the space of $X$,

$$
\sum_{i = 1}^{n} p(x_i) = 1
$$

As it turns out, we can't do this for continuous variables because the values in their space aren't countable. In other words, we can't list out all the values of a continuous random variable, and therefore, it's not possible to ensure this property holds. Let's dig into this a little further to make it clearer. Turning our attention back to our random variable with space $0 \leq X \leq 1$, let's try to count all the values between 0 and 1. Suppose we enumerate (or believe we have enumerated) all the values, e.g.,

$$
0.123451...\\
0.234672...\\
0.247773...\\
0.866724...\\
0.999525...
$$

We line our list up with the natural numbers and begin counting the numbers between zero and one. 

$$
1) \:\: 0.123451...\\
2) \:\: 0.234672...\\
3) \:\: 0.247773...\\
4) \:\: 0.866724...\\
5) \:\: 0.999525...
$$

But to our surprise (or maybe to our non-surprise) there will *always* be a number we missed during our enumeration. Note the underlined numbers in our list below.

$$
1) \:\: 0.\underline{1}23451...\\
2) \:\: 0.2\underline{3}4672...\\
3) \:\: 0.24\underline{7}773...\\
4) \:\: 0.866\underline{7}24...\\
5) \:\: 0.9995\underline{2}5...
$$

We can specify a new number $0.abcde$ such that a, b, c, d, and e are numbers between 0 and 9, representing the first through fifth digits, respectively. To make sure our number is new, we ensure that $a \neq 1$, $b \neq 3$, $c \neq 7$, $d \neq 7$, and $e \neq 2$. Thus the first digit will differ from that of the first listed number, the second digit will differ from that of the second listed number, and so on. Our new number is therefore different from each of the enumerated numbers. No matter how certain we were in the thoroughness of our list, we would always have to go back and account for a newly discovered number. They simply cannot be counted.

The logic described above, attributed to Georg Cantor a famous set theorist, is indeed intriguing, but why is it important for our purposes? Well, it tells us that we can't specify probability distributions for continuous random variables in the way that we define them for discrete random variables. You can't sum the probability of each outcome - $p(x_1)$ - over the set of outcomes because we can't list out the outcomes. And, therefore, we couldn't ensure we've attained the important property of $\sum_{i = 1}^{n} p(x_i) = 1$.  

As it turns out, we get around this conundrum by assigning probabilities to *ranges* of our continuous random variable. We do this with a **probability density function**. A probability density function describes the amount of probability per unit $x$ at a given point. This is not an immediately accessible point, so we'll dig deeper into this concept as we have in the past - through an example. Let's define a probability density function

$$
f(x) = 
\begin{cases}
1 & 0 \leq x \leq 1 \\
0 & Everywhere \: else
\end{cases}
$$

This function assigns a value of 1 probability density to any value - $0 \leq x \leq 1$. Anywhere else it assigns a value of 0. Thus, suppose our value of $x - .1$, then

$$
f(.1) = 1 
$$

Let's refer to units of probability mass with the abbreviation - $pm$ - and let's assume that the units of $x$ are $u$ (short for units of x). The value of 1 from the equation above has the units $pm/u$, e.g., probability mass per units of x. That is to say, our probability density function is describing the amount of probability mass per unit x at exactly the point $x = .1$. Now let's talk about how such a function assigns probability to a range of x. First, let's take a look at the plot of our probability density function

```{r, echo = FALSE}
a <- data.frame(x = c(0), 
                y = c(1),
                x_end = 1,
                y_end = 1)
                

ggplot2::ggplot(a, ggplot2::aes(x = x, y = y)) +
  ggplot2::geom_segment(data = a, ggplot2::aes(x = x, y = y, xend = x_end, yend = y_end)) +
  ggplot2::scale_y_continuous(limits = c(0,2)) +
  ggplot2::scale_x_continuous(limits = c(0,1.5)) +
  ggplot2::labs(y = "y (pm/u)", x = "x (u)")


```

Indeed, it is a very boring plot - just a straight line. 